@echo off
echo Building...
if exist autogenerated.exe del autogenerated.exe
pyinstaller --onefile --add-data "bin;bin" autogenerated.py
xcopy dist\autogenerated.exe . /s /y /i
if exist dist rd /s /q dist
if exist build rd /s /q build
if exist autogenerated.spec del autogenerated.spec
echo Build complete.
pause